#  menu items

[[main]]
  name = "Demo API"
  weight = 1
  url = "demo-api/"

[[main]]
  name = "Downloads"
  weight = 2
  url = "downloads/"

[[main]]
  name = "Resources"
  weight = 3
  url = "resources/"
